import type { Job } from "@/lib/types";

function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

export async function executeJob(job: Job, onProgress: (message: string) => Promise<void>) {
  // TODO: Replace this mock executor with sandboxed adapters for approved job types.
  await onProgress("Loading local runtime");
  await sleep(1000);

  await onProgress(`Executing ${job.type}`);
  await sleep(1000);

  if (job.type === "shell_demo") {
    return `Mock shell output for input: ${job.input}`;
  }

  if (job.type === "embedding") {
    return JSON.stringify({ embedding: [0.12, 0.42, 0.87], inputLength: job.input.length });
  }

  if (job.type === "image_caption") {
    return "Mock caption: a concise description generated by the provider machine.";
  }

  return `Mock text result: ${job.input}\n\nSummary:\n- Local agent received the job\n- The job ran on a provider machine\n- Results were returned to GPUbnb`;
}
